apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-curl
  namespace: client
spec:
  initconatainer:
    - name: init-curl
      image: curl:latest
      commands: ["curl","http://springboot-service.springboot-app.svc.cluster.local:8083/datasetapis"]
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["sleep","infinity"]