apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8083 #port number exposes internally in the cluster
      targetPort: 8083 #port the container on listening
      nodePort: 30008 #access service via external port number