apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  SPRING_DATASOURCE_URL: "{{ .Values.configmap.data.SPRING_DATASOURCE_URL }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.configmap.data.SPRING_DATASOURCE_USERNAME }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.configmap.data.SPRING_DATASOURCE_PASSWORD }}"

