apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.volumes.name }}
  namespace: {{ .Values.postgres.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.volumes.storage }}
